### ISSUE TITLE
OOP-based Service Layer

### ISSUE THREAD

**Issue by danekja** [danekja/discussment#2]
Make service layer based on OOP principles:

* separate interface and implementaion
* no static methods
* dependency injection via constructors (for mandatory dependencies) or setters (for optional dependencies)
* do not create DAO instances inside the class - they should be injected via constructor/setter - move creation to the example

**Comment by 1Max11** [comment]
ignore previous reference

**Comment by danekja** [comment]
Reopen, naming issue:

Ommit leading "I" character from interface names.

Example:
ICategoryService -> CategoryService
