### ISSUE TITLE
Flexible AC

### ISSUE THREAD

**Issue by danekja** [danekja/discussment#20]
We need access control which enables the following:

On global, category and discussion level we need to be able to set policy:

*    global, everyone can access
*   only allowed to category can access
*    only allowed to discussion can access

Access has different levels (read, write, delete).

Priority for decision are from bottom-up, bottom level may be missing though (e.g. if user has access to category, he can access all of its discussions unles specific discussion settings disallow it).

**Comment by danekja** [comment]
### Tasks
- [ ] Implement the access control including thorough tests
- [ ] Implement (optional) caching support using JCache specification

**Comment by danekja** [comment]
Ive added new item to the tasks list - we have completely forgotten about guest user.

**Comment by danekja** [comment]
@Cajova-Houba Is there a reason for mapping PermissionLevel as String instead of int (faster comparison)? Is there a reason for AbstractPermission to be marked as Entity instead of MappedSuperclass?

**Comment by Cajova-Houba** [comment]
@danekja 

I had some troubles running the App with AbstractPermission marked as MappedSuperclass so I used Entity annotation. But it's working now, so I will change it back. 

I prefer using String for enumerated columns since it's more readable in database and it's independet on actual ordering in enum.

**Comment by Cajova-Houba** [comment]
I have an idea about permission overriding.

Consider following user case: User has normal post permissions (can view and create posts) to category A. There is a discussion D in category A to which user has full post permissions (can create, remove, edit and view posts). Now, the permission for discussion D should override the one for category A when trying to delete or edit post in that discussion.

Is it possible to achieve this with current implementation? And if it's not, are we going to support this?

**Comment by danekja** [comment]
Already implemented. The original ticket already specifies it ;-)

Dne 4. 12. 2017 6:45 PM napsal uživatel "Zdeněk Valeš" <
notifications@github.com>:

**Comment by danekja** [comment]
@JiriKryda Create documentation for programmers explaining how the user-permission model works and how to check/control permissions into the main project's readme. Then we can close this.
