### ISSUE TITLE
Like/Dislike Feature for Posts

### ISSUE THREAD

**Issue by danekja** [danekja/discussment#22]
# User Story
As Post Reader, I want to be able to mark whether I like or dislike post. Also, I want to see how many people have liked/disliked the post.

As Post Author, I cannot be allowed to like/dislike my own posts.

## Discussion
Should we have special permissions for this feature or should it be bound to read (or write?) permission? Or should everyone be allowed to vote, if global module's configuration allows voting? What do you think @Cajova-Houba,  @fidransky ?

**Comment by Cajova-Houba** [comment]
I think everyone with view permission should be able to vote, because if I can see something, I would like to have the ability to express my opinion. On the other hand, if we have a special permission for voting, the app is going to be generic and someone might later use it as a feature.
