### ISSUE TITLE
Default category and topic

### ISSUE THREAD

**Issue by danekja** [danekja/discussment#24]
I think we need to add default category and topic objects. All discussions which belong to "no category" or "no topic" would be attached to them (instead of having those values null).

Why? Because Having null topic for discussions or null category for topics would require multiple different queries based on whether the parameter is null or not. Same would go for certain places in business logic and UI. Whereas with default category and topic, we can use same logic and UI views for everything without any conditions. With proper indexes, the performance drawback should be minimal and application's architecture would be simple.

What do you think @Cajova-Houba and @fidransky?

**Impacts**: #20 Flexible AC

**Comment by Cajova-Houba** [comment]
I think it's a good idea which simplifies business logic (no need to handle discussions / topics separately). Also, no changes would be required for the current implementation of AC. We should definitely do this.

**Comment by danekja** [comment]
@JiriKryda this has been implemented in the ACL branch, correct?
