### ISSUE TITLE
Java 7 support

### ISSUE THREAD

**Issue by fidransky** [danekja/discussment#36]
Create a new version of core which can be run using JDK 1.7 meaning it should not use any Java 8 features.

**Comment by danekja** [comment]
Lets make it like this:

- both core and wicket ui modules
- we will compile with JDK7 as target to ensure no JDK8 features are used
- we can use qualifier to distinguish the build, no qualifier defaults to JDK8

**Comment by danekja** [comment]
Done in code, now we need:

- [ ] Documentation of release process to maintain sanity
- [ ] Release into mvn central (probably with 1.0)
