### ISSUE TITLE
Cannot save entity pointing to Discussion

### ISSUE THREAD

**Issue by fidransky** [danekja/discussment#56]
When trying to save an entity which has `OneToOne` relation with Discussion, it fails with the following exception being thrown:

```
No row with the given identifier exists: [org.danekja.discussment.core.domain.Discussion#104]
```

In code, the Discussion is saved successfully first and it is attached to the entity then. However, saving the entity fails.

The problem seems to be that both saves occur in one transaction. In Hibernate, the transaction is commited after whole saving method is finished. It means that the Discussion is NOT in database yet when Hibernate tries to save the entity even though it is about to be stored successfully.

**Comment by danekja** [comment]
Hm, this is kinda weird. Transaction should still be able to commit. But, it may have something to do with mismatch between primary key generator used by hibernate and by the database (i.e. the primary key generated before transaction commit is different from the one generated during the commit).

**Comment by fidransky** [comment]
I thought it should but it just doesnt work. It might also be some clash between the two versions of Hibernate.

The fix is pretty simple and it should (hopefully) not break anything, see the PR.

**Comment by danekja** [comment]
Just out of curiosity, can I see the code which fails?

**Comment by fidransky** [comment]
Some details are ommited for brevity.

**entity**

```java
    @OneToOne(cascade = CascadeType.REMOVE, orphanRemoval = true)
    @JoinColumn(name = "discussion_id")
    public Discussion getDiscussion() {
        return discussion;
    }
```

**manager**

```java
private Notification createNewNotificationForSocietyInternal(Notification notification) throws Exception {
    // create discussion
    Topic topic = topicService.getDefaultTopic();
    Discussion discussion = new Discussion(notification.getHeader());

    discussion = discussionService.createDiscussion(topic, discussion);

    //create notification
    notification.setDiscussion(discussion);

    notification = notificationDao.save(notification);

    return notification;
}
```
