### ISSUE TITLE
Wicket UI improvements

### ISSUE THREAD

**Issue by Cajova-Houba** [danekja/discussment#78]
Fix N+1 problem when rendering post hierarchy by loading post hierarchy once.

**Comment by Cajova-Houba** [comment]
Goals of related refactoring

 - Get rid of N+1
 - Simplify ACL checks, following rule is to be applied: users which can see the discussion can also read and create new posts in that discussion
 - Overridable handlers for sending new posts and replies

**Comment by Cajova-Houba** [comment]
What needs to be fetched in bulk in order to prevent N+1:

 - Post's author (name at least)

Also, actions such as like or dislike should not refresh the whole page.

**Comment by Cajova-Houba** [comment]
Note: It is assumed that `DiscussionUserService.getCurrentlyLoggedUser()` does not call DB or API and calls to that method are not considered as causes of N+1.

**Comment by Cajova-Houba** [comment]
How to load post's author  without causing N+1:

Add method to `PostService` which will take a list of post ids as input and returns a collection of users which are authors of these posts. 

This approach doesn't mess with the data model and is backwards compatible.

**Comment by fidransky** [comment]
Solved by [this PR](https://github.com/fidransky/discussment/pull/1).
