### ISSUE TITLE
Ajax-based form for sending posts

### ISSUE THREAD

**Issue by Cajova-Houba** [danekja/discussment#94]
Currently, the `PostForm` (component responsible for sending posts) is just plain form. The page gets refreshed every time the form gets submitted. This causes problems when used in combination with modal windows as they get closed and have to be re-openned again. The solution is to make `PostForm` ajax-based.

**Comment by Cajova-Houba** [comment]
While I'm at it I can also fix text area resizing in `PostFormComponent`. Only vertical resize should be sllowed to prevent this
![text-area-resize](https://user-images.githubusercontent.com/6975241/88172198-df900980-cc20-11ea-9263-44d037276273.png)
:

**Comment by fidransky** [comment]
@Cajova-Houba Let's do nothing here. Resizing is desirable in some contexts and we should not disable it by default.

If we want to disable it in MN, we should override the markup in MN and add necessary styling there.
